const dummyData = [
    {
        title: "Product 1",
        description: "Description for Product 1.",
        price: 19.99,
        stock: 15,
        images: [
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
        ],
        category: "chemicals",
    },
    {
        title: "Product 2",
        description: "Description for Product 2.",
        price: 29.99,
        stock: 8,
        images: [
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
        ],
        category: "chemicals",
    },
    {
        title: "Product 3",
        description: "Description for Product 3.",
        price: 39.99,
        stock: 20,
        images: [
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
        ],
        category: "chemicals",
    },
    {
        title: "Product 4",
        description: "Description for Product 4.",
        price: 49.99,
        stock: 12,
        images: [
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
        ],
        category: "chemicals",
    },
    {
        title: "Product 5",
        description: "Description for Product 5.",
        price: 59.99,
        stock: 18,
        images: [
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
        ],
        category: "chemicals",
    },
    {
        title: "Product 6",
        description: "Description for Product 6.",
        price: 69.99,
        stock: 25,
        images: [
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
        ],
        category: "chemicals",
    },
    {
        title: "Product 7",
        description: "Description for Product 7.",
        price: 79.99,
        stock: 5,
        images: [
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
        ],
        category: "chemicals",
    },
    {
        title: "Product 8",
        description: "Description for Product 8.",
        price: 89.99,
        stock: 30,
        images: [
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
        ],
        category: "chemicals",
    },
    {
        title: "Product 9",
        description: "Description for Product 9.",
        price: 99.99,
        stock: 7,
        images: [
            { ur1: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
        ],
        category: "chemicals",
    },
    {
        title: "Product 10",
        description: "Description for Product 10.",
        price: 109.99,
        stock: 22,
        images: [
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
            { url: "https://www.shutterstock.com/image-photo/variety-fresh-organic-vegetables-fruits-260nw-439784905.jpg" },
        ],
        category: "chemicals0",
    },
];

export default  dummyData